name: Make Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Windows ---
          - platform: windows/amd64
            args: -upx
            ext: .exe
          - platform: windows/386
            args: -upx
            ext: .exe
          # --- Linux ---
          - platform: linux/amd64
            args: -upx
            ext: ""


    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Tools & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y upx
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          sudo apt-get install -y mingw-w64

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Binary
        shell: bash
        run: |
          PLATFORM_NAME=$(echo ${{ matrix.platform }} | tr / -)
          FILENAME="JNU-EXAM-Downloader-${{ github.ref_name }}-${PLATFORM_NAME}${{ matrix.ext }}"
          echo "Building target: $FILENAME ..."
          
          wails build \
            -platform ${{ matrix.platform }} \
            -clean \
            ${{ matrix.args }} \
            -o "$FILENAME"

          cd build/bin
          
          sha256sum "$FILENAME" | awk '{print $1}' > "$FILENAME.sha256"
          
          echo "SHA256 generated for $FILENAME"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/bin/*
          prerelease: ${{ contains(github.ref, '-') }}
          draft: false
    
  build-windows-arm64:
    name: Build Windows ARM64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build
        shell: bash
        run: |
          FILENAME="JNU-EXAM-Downloader-${{ github.ref_name }}-windows-arm64.exe"
          
          echo "Building target: $FILENAME ..."

          wails build -platform windows/arm64 -clean -o "$FILENAME"
          
          cd build/bin
          sha256sum "$FILENAME" | awk '{print $1}' > "$FILENAME.sha256"
          
          echo "SHA256 generated for $FILENAME"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/JNU-EXAM-Downloader-${{ github.ref_name }}-windows-arm64.exe
            build/bin/JNU-EXAM-Downloader-${{ github.ref_name }}-windows-arm64.exe.sha256
          prerelease: ${{ contains(github.ref, '-') }}
  