name: Release (x86/x64)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Windows ---
          - platform: windows/amd64
            args: -upx
            ext: .exe
          - platform: windows/386
            args: -upx
            ext: .exe
          # --- Linux ---
          - platform: linux/amd64
            args: -upx 
            ext: ""


    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Tools & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y upx
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
          sudo apt-get install -y mingw-w64

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Binary
        run: |
          PLATFORM_NAME=$(echo ${{ matrix.platform }} | tr / -)
          
          echo "Building for ${{ matrix.platform }}..."
          
          wails build \
            -platform ${{ matrix.platform }} \
            -clean \
            ${{ matrix.args }} \
            -o JNU-EXAM-Downloader-${PLATFORM_NAME}${{ matrix.ext }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/bin/*
          prerelease: ${{ contains(github.ref, '-') }}
          draft: false